apiVersion: v1
kind: Namespace
metadata:
  name: rag-app
  labels:
    app.kubernetes.io/name: citeshield
    kubernetes.io/metadata.name: rag-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: vector-db
  labels:
    app.kubernetes.io/name: citeshield
    kubernetes.io/metadata.name: vector-db
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: citeshield
    kubernetes.io/metadata.name: monitoring
