resources:
  - ../../base
  - secret.dev.yaml
patches:
  - target:
      kind: Deployment
      name: citeshield-api
      namespace: rag-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: citeshield-api:local
