apiVersion: v1
kind: Secret
metadata:
  name: citeshield-app-secrets
  namespace: rag-app
type: Opaque
stringData:
  TENANT_A_API_KEY: tenant-a-dev-key
  TENANT_B_API_KEY: tenant-b-dev-key
  SUPERUSER_API_KEY: superuser-dev-key
